### ISSUE TITLE
Mac OS issues

### ISSUE THREAD

**Issue by mare-imbrium** [buffet/filet#11]
Compilation errors for `HOST_NAME_MAX` and `SIGWINCH`.
I compiled successfully after putting in dummy values.

However, the `h` and left-arrow don't work. I have no way of leaving a directory. Actually, the `h` key takes me to the top of the list. Left-arrow does nothing.

Copying in errors since file attaching doesn't work sometimes.
[errors.txt](https://github.com/buffet/filet/files/2939750/errors.txt)

```
filet.c:51:24: warning: unused parameter 'sb' [-Wunused-parameter]
    const struct stat *sb,
                       ^
filet.c:52:9: warning: unused parameter 'typeflag' [-Wunused-parameter]
    int typeflag,
        ^
filet.c:53:17: warning: unused parameter 'ftwbuf' [-Wunused-parameter]
    struct FTW *ftwbuf)
                ^
filet.c:429:29: error: use of undeclared identifier 'HOST_NAME_MAX'
    char *hostname = malloc(HOST_NAME_MAX);
                            ^
filet.c:434:31: error: use of undeclared identifier 'HOST_NAME_MAX'
    if (gethostname(hostname, HOST_NAME_MAX) < 0) {
                              ^
filet.c:451:16: error: use of undeclared identifier 'SIGWINCH'
    if (signal(SIGWINCH, handle_winch) == SIG_ERR) {
               ^
3 warnings and 3 errors generated.
make: *** [filet] Error 1
```

**Comment by buffet** [comment]
Hey! Which version did you compile, and what did you put for dummy values?

The SIGWINCH should be fixed by trying to compile the latest master instead (which actually fixes a few issues).

I will look into the hostname and the 'h' problem later.

**Comment by buffet** [comment]
Release 0.1.2 fixes the issue with 'h'. As for the `HOST_NAME_MAX` problem that will be fixed soon, hopefully. Setting it to a value bigger than your hostname would be the solution for now sadly.

**Comment by mare-imbrium** [comment]
> Hey! Which version did you compile, and what did you put for dummy values?
> 
> The SIGWINCH should be fixed by trying to compile the latest master instead (which actually fixes a few issues).
> 
> I will look into the hostname and the 'h' problem later.

The SIGWINCH still gives an error. But I put the following and it works fine.

    #define SIGWINCH        28

I am downloading from `master`. 
I used 128 for HOSTNAME but 256 should be fine.

**Comment by buffet** [comment]
I kinda messed up when I thought master had it fixed.

It's some weird issue, setting it to 28 seems to be the valid fix though, even though it's super ugly and I hate it.
