### ISSUE TITLE
Shell scripts open in a web browser

### ISSUE THREAD

**Issue by Ved-un** [buffet/filet#18]
Hello. Thank you for the program.

Why do shell scripts open in my web browser instead of in a text editor?

**Comment by buffet** [comment]
Do you have an example? If you haven't set `FILET_OPENER` it defaults to xdg-open.

**Comment by Ved-un** [comment]
I have export FILET_OPENER=xdg-open set, but the point files open in Firefox.

Now I checked and found out that only shell scripts open in browser, but plain text files open fine in text editor.

**Comment by buffet** [comment]
I can't really reproduce this, and I also really don't know anything about xdg-open. It seems you want to change your default handler maybe to be your editor, but I'm really not sure.

Either way, this isn't really a problem with filet, and sadly I cannot help you resolve it.

**Comment by Ved-un** [comment]
I don't know.
The problem must be in the **filet** code.

I have all file managers (**cfm, shfm, pcmanfm** etc) open shell scripts in default text editor (**micro**) and only **filet** opens them in browser ))

I will not argue with you and will use my old and proven programs.
Have a nice day.
