### ISSUE TITLE
Open files

### ISSUE THREAD

**Issue by Recidiviste** [buffet/filet#7]
How can i open files ?
You said we have to do something with `xdg-open`
But i think i' kinda a newbie (:sweat_smile:), so i must say that i don't understand what you're saying.
I've found the file filet.c, i've edited it to add my editor, my shell, my home, but for opener, i don't know what to do.

Thanks anyway

**Comment by buffet** [comment]
Hey! Took longer than I expected until someone asked this.

filet takes all that stuff from your environment. This means you do not need to modify the source. You can set the EDITOR shell variable to whatever editor you prefer (`EDITOR=nano` for example) and filet will use that.

SHELL and HOME are set by your environment automatically. To check any of these values you can run `echo $SHELL`.

FILET_OPENER is the only variable introduced by filet itself. To set it to `xdg-open` just put `FILET_OPENER=xdg-open` in your .bashrc, after making sure `xdg-open` is available on your system (`command -v xdg-open || echo xdg-open is missing` to test).

I hope this makes it somewhat clear. I should add `xdg-open` as default to be honest.

**Comment by Recidiviste** [comment]
I use the shell fish, so i add the variable $FILET_OPENER
Doesn't do the thing, so i tried to change the .bashrc file
But i think i'm a dick, so nothing happens. 
And now, i make it works by editing the `filet.c` file and re `make` it.
Here's my edit :
`   
    const char *opener = getenv_or("FILET_OPENER","xdg-open");
`
I just add the `_or` and the `xdg-open`, and it works just fine :smiley: !

**Comment by buffet** [comment]
That's what I meant. The `getenv_or` function tries to get what's behind the given name, and defaults to the second value.

For `fish` you need to `set -x FILET_OPENER xdg-open` in `~/.config/fish/config.fish`.

If the patched version works for you that's also fine. You'd need to patch it every time you want to update though, so keep that in mind.

**Comment by buffet** [comment]
@Recidiviste Can this issue be closed?

**Comment by Recidiviste** [comment]
Sure, the issue is considered as close for me at the time i add the _or :rofl:

**Comment by buffet** [comment]
Just leaving a note for the future: FILET_OPENER defaults to `xdg-open` now. If it doesn't work you probably don't have it installed.
